"""baseline schema

Revision ID: 7940ce23d545
Revises:
Create Date: 2026-10-02 20:34:23.581873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7940ce23d545'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('budget_limit_cents', sa.Integer(), nullable=True),
    sa.Column('quoted_amount_cents', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('replikers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('base_price_credits', sa.Integer(), nullable=False),
    sa.Column('balance_credits', sa.Integer(), nullable=False),
    sa.Column('total_earnings_credits', sa.Integer(), nullable=False),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replikers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replikers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replikers_owner_id'), ['owner_id'], unique=False)

    op.create_table('ledger_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_key', sa.String(length=180), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(kind IN ('user_available', 'user_pending') AND user_id IS NOT NULL AND project_id IS NULL) OR (kind = 'project_custody' AND project_id IS NOT NULL AND user_id IS NULL) OR (kind IN ('platform_revenue', 'system_clearing') AND user_id IS NULL AND project_id IS NULL)", name='ck_ledger_account_owner'),
    sa.CheckConstraint("kind IN ('user_available', 'user_pending', 'project_custody', 'platform_revenue', 'system_clearing')", name='ck_ledger_account_kind'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_key', name='uq_ledger_account_key')
    )
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_account_project_kind_currency', ['project_id', 'kind', 'currency'], unique=False)
        batch_op.create_index('ix_ledger_account_user_kind_currency', ['user_id', 'kind', 'currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_account_key'), ['account_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('project_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_requirements_project_id'), ['project_id'], unique=False)

    op.create_table('repliker_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('avatar_style', sa.String(length=50), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('face_type', sa.String(length=50), nullable=False),
    sa.Column('eye_style', sa.String(length=50), nullable=False),
    sa.Column('accessory', sa.String(length=80), nullable=False),
    sa.Column('background_style', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repliker_id', name='uq_repliker_appearance')
    )
    with op.batch_alter_table('repliker_appearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repliker_appearances_repliker_id'), ['repliker_id'], unique=False)

    op.create_table('repliker_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repliker_id', 'name', name='uq_repliker_skill')
    )
    with op.batch_alter_table('repliker_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repliker_skills_repliker_id'), ['repliker_id'], unique=False)

    op.create_table('repliker_tool_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repliker_id', 'tool_name', name='uq_repliker_tool_assignment')
    )
    with op.batch_alter_table('repliker_tool_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repliker_tool_assignments_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repliker_tool_assignments_tool_name'), ['tool_name'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('max_budget_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('agent_activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('repliker_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_activity_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activity_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activity_events_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activity_events_task_id'), ['task_id'], unique=False)

    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('sender_type', sa.String(length=30), nullable=False),
    sa.Column('sender_repliker_id', sa.Integer(), nullable=True),
    sa.Column('receiver_type', sa.String(length=30), nullable=False),
    sa.Column('receiver_repliker_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_repliker_id'], ['replikers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_repliker_id'], ['replikers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_receiver_repliker_id'), ['receiver_repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_sender_repliker_id'), ['sender_repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_task_id'), ['task_id'], unique=False)

    op.create_table('realtime_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('repliker_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('activity', 'message', 'workflow', 'economy', 'system')", name='ck_realtime_event_kind'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realtime_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_realtime_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_events_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_events_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_realtime_project_cursor', ['project_id', 'id'], unique=False)
        batch_op.create_index('ix_realtime_repliker_cursor', ['repliker_id', 'id'], unique=False)

    op.create_table('repliker_task_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'repliker_id', name='uq_repliker_task_decision')
    )
    with op.batch_alter_table('repliker_task_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repliker_task_decisions_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repliker_task_decisions_task_id'), ['task_id'], unique=False)

    op.create_table('task_acceptance_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_acceptance_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_acceptance_criteria_task_id'), ['task_id'], unique=False)

    op.create_table('task_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'repliker_id', name='uq_task_repliker_bid')
    )
    with op.batch_alter_table('task_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_bids_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_bids_task_id'), ['task_id'], unique=False)

    op.create_table('task_skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('minimum_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_skill_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_skill_requirements_task_id'), ['task_id'], unique=False)

    op.create_table('task_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reserved_cents', sa.Integer(), nullable=False),
    sa.Column('skill_score', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('price_score', sa.Integer(), nullable=False),
    sa.Column('time_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('selection_score', sa.Integer(), nullable=False),
    sa.Column('selected_by', sa.String(length=30), nullable=False),
    sa.Column('selection_policy_version', sa.String(length=30), nullable=False),
    sa.Column('selection_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_task_contract_amount_positive'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 100', name='ck_task_contract_confidence_score'),
    sa.CheckConstraint('price_score BETWEEN 0 AND 100', name='ck_task_contract_price_score'),
    sa.CheckConstraint('reputation_score BETWEEN 0 AND 100', name='ck_task_contract_reputation_score'),
    sa.CheckConstraint('reserved_cents >= 0', name='ck_task_contract_reserved_nonnegative'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_task_contract_risk_score'),
    sa.CheckConstraint('selection_score BETWEEN 0 AND 100', name='ck_task_contract_selection_score'),
    sa.CheckConstraint('skill_score BETWEEN 0 AND 100', name='ck_task_contract_skill_score'),
    sa.CheckConstraint('time_score BETWEEN 0 AND 100', name='ck_task_contract_time_score'),
    sa.ForeignKeyConstraint(['bid_id'], ['task_bids.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_task_contract_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_contracts_bid_id'), ['bid_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_task_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_contracts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_contracts_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_contracts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_contracts_task_id'), ['task_id'], unique=False)
        batch_op.create_index('uq_task_contract_active', ['task_id'], unique=True, sqlite_where=sa.text("status IN ('awarded', 'active')"), postgresql_where=sa.text("status IN ('awarded', 'active')"))

    op.create_table('collaboration_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_type', sa.String(length=30), nullable=False),
    sa.Column('created_by_repliker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('task_execution', 'client_coordination', 'delegation', 'qa', 'handoff', 'incident')", name='ck_collaboration_thread_kind'),
    sa.CheckConstraint("status IN ('open', 'blocked', 'waiting', 'resolved', 'closed')", name='ck_collaboration_thread_status'),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_repliker_id'], ['replikers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'kind', name='uq_collaboration_contract_kind')
    )
    with op.batch_alter_table('collaboration_threads', schema=None) as batch_op:
        batch_op.create_index('ix_collaboration_thread_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('ix_collaboration_thread_task', ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_threads_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_threads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_threads_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_threads_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_threads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_threads_task_id'), ['task_id'], unique=False)

    op.create_table('execution_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('storage_driver', sa.String(length=30), nullable=False),
    sa.Column('root_ref', sa.String(length=180), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=False),
    sa.Column('max_file_bytes', sa.Integer(), nullable=False),
    sa.Column('max_total_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_ref')
    )
    with op.batch_alter_table('execution_workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_workspaces_contract_id'), ['contract_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_execution_workspaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_workspaces_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_workspaces_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_workspaces_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_workspaces_task_id'), ['task_id'], unique=False)

    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('repliker_id', sa.Integer(), nullable=True),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('funding', 'allocation', 'earning', 'commission', 'refund', 'withdrawal', 'reversal', 'adjustment')", name='ck_ledger_transaction_type'),
    sa.CheckConstraint('amount_cents > 0', name='ck_ledger_transaction_positive'),
    sa.CheckConstraint('from_account_id <> to_account_id', name='ck_ledger_transaction_distinct_accounts'),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_account_id'], ['ledger_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['ledger_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_ledger_transaction_idempotency')
    )
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_transaction_contract', ['contract_id'], unique=False)
        batch_op.create_index('ix_ledger_transaction_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ledger_transaction_repliker', ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_from_account_id'), ['from_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_initiated_by_user_id'), ['initiated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_to_account_id'), ['to_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('collaboration_message_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), nullable=False),
    sa.Column('requires_ack', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("delivery_status IN ('sent', 'acknowledged', 'resolved')", name='ck_collaboration_delivery_status'),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name='ck_collaboration_message_priority'),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['agent_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['collaboration_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_message_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaboration_message_states_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_message_states_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_collaboration_message_states_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_message_states_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_collaboration_state_thread_status', ['thread_id', 'delivery_status'], unique=False)

    op.create_table('collaboration_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('participant_key', sa.String(length=100), nullable=False),
    sa.Column('participant_type', sa.String(length=30), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['collaboration_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'participant_key', name='uq_collaboration_participant')
    )
    with op.batch_alter_table('collaboration_participants', schema=None) as batch_op:
        batch_op.create_index('ix_collaboration_participant_repliker', ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_participants_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_participants_thread_id'), ['thread_id'], unique=False)

    op.create_table('delegation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.String(length=240), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('root_contract_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('parent_request_id', sa.Integer(), nullable=True),
    sa.Column('delegator_repliker_id', sa.Integer(), nullable=False),
    sa.Column('collaboration_thread_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('required_skill_name', sa.String(length=100), nullable=False),
    sa.Column('minimum_skill_level', sa.Integer(), nullable=False),
    sa.Column('max_budget_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IN ('delegate', 'do_self')", name='ck_delegation_decision'),
    sa.CheckConstraint("status IN ('requested', 'awarded', 'active', 'rejected', 'cancelled', 'completed')", name='ck_delegation_status'),
    sa.CheckConstraint('depth >= 1', name='ck_delegation_depth_positive'),
    sa.CheckConstraint('max_budget_cents > 0', name='ck_delegation_budget_positive'),
    sa.ForeignKeyConstraint(['collaboration_thread_id'], ['collaboration_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delegator_repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_request_id'], ['delegation_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delegation_requests', schema=None) as batch_op:
        batch_op.create_index('ix_delegation_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_collaboration_thread_id'), ['collaboration_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_delegation_requests_delegator_repliker_id'), ['delegator_repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_parent_request_id'), ['parent_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_root_contract_id'), ['root_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_requests_status'), ['status'], unique=False)

    op.create_table('execution_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('media_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['execution_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'relative_path', name='uq_execution_artifact_path')
    )
    with op.batch_alter_table('execution_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_artifacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_artifacts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('qa_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('execution_repliker_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_repliker_id', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reviewer_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('prepared', 'running', 'passed', 'failed', 'needs_review')", name='ck_qa_review_status'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_qa_review_attempt_positive'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_qa_review_score'),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['execution_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'attempt_number', name='uq_qa_review_contract_attempt')
    )
    with op.batch_alter_table('qa_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_reviews_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reviews_execution_repliker_id'), ['execution_repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reviews_reviewer_repliker_id'), ['reviewer_repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reviews_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reviews_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('tool_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('target_path', sa.String(length=1000), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['execution_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_execution_logs_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_execution_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_execution_logs_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_execution_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_execution_logs_tool_name'), ['tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_execution_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('delegated_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegation_request_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('required_skill_name', sa.String(length=100), nullable=False),
    sa.Column('minimum_skill_level', sa.Integer(), nullable=False),
    sa.Column('max_budget_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'assigned', 'active', 'completed', 'failed', 'cancelled')", name='ck_delegated_task_status'),
    sa.CheckConstraint('complexity BETWEEN 1 AND 100', name='ck_delegated_task_complexity'),
    sa.CheckConstraint('max_budget_cents > 0', name='ck_delegated_task_budget'),
    sa.ForeignKeyConstraint(['delegation_request_id'], ['delegation_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delegated_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_delegated_task_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegated_tasks_delegation_request_id'), ['delegation_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delegated_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegated_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegated_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegated_tasks_status'), ['status'], unique=False)

    op.create_table('qa_criterion_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'passed', 'failed', 'needs_review')", name='ck_qa_criterion_status'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_qa_criterion_score'),
    sa.ForeignKeyConstraint(['criterion_id'], ['task_acceptance_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['qa_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'criterion_id', name='uq_qa_result_review_criterion')
    )
    with op.batch_alter_table('qa_criterion_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_criterion_results_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_criterion_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_criterion_results_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_criterion_results_status'), ['status'], unique=False)

    op.create_table('qa_reputation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('jobs_completed_before', sa.Integer(), nullable=False),
    sa.Column('jobs_completed_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("outcome IN ('passed', 'failed', 'needs_review')", name='ck_qa_reputation_outcome'),
    sa.CheckConstraint('delta BETWEEN -10 AND 10', name='ck_qa_reputation_delta'),
    sa.CheckConstraint('jobs_completed_after >= 0', name='ck_qa_reputation_jobs_after'),
    sa.CheckConstraint('jobs_completed_before >= 0', name='ck_qa_reputation_jobs_before'),
    sa.CheckConstraint('score_after BETWEEN 0 AND 100', name='ck_qa_reputation_after'),
    sa.CheckConstraint('score_before BETWEEN 0 AND 100', name='ck_qa_reputation_before'),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['qa_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', name='uq_qa_reputation_review')
    )
    with op.batch_alter_table('qa_reputation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_reputation_events_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reputation_events_repliker_id'), ['repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_reputation_events_review_id'), ['review_id'], unique=True)

    op.create_table('qa_retry_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('source_review_id', sa.Integer(), nullable=False),
    sa.Column('next_review_id', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('execution_status', sa.String(length=40), nullable=False),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'execution_failed', 'exhausted')", name='ck_qa_retry_status'),
    sa.CheckConstraint('artifact_count >= 0', name='ck_qa_retry_artifact_count'),
    sa.CheckConstraint('attempt_number >= 2', name='ck_qa_retry_attempt'),
    sa.ForeignKeyConstraint(['contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_review_id'], ['qa_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_review_id'], ['qa_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_review_id', name='uq_qa_retry_source_review')
    )
    with op.batch_alter_table('qa_retry_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_retry_runs_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_retry_runs_next_review_id'), ['next_review_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_qa_retry_runs_source_review_id'), ['source_review_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_qa_retry_runs_status'), ['status'], unique=False)

    op.create_table('delegation_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegated_task_id', sa.Integer(), nullable=False),
    sa.Column('repliker_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('skill_score', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('price_score', sa.Integer(), nullable=False),
    sa.Column('experience_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('selection_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pricing_policy_version', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_delegation_offer_amount'),
    sa.CheckConstraint('selection_score BETWEEN 0 AND 100', name='ck_delegation_offer_score'),
    sa.ForeignKeyConstraint(['delegated_task_id'], ['delegated_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repliker_id'], ['replikers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delegated_task_id', 'repliker_id', name='uq_delegation_offer_task_repliker')
    )
    with op.batch_alter_table('delegation_offers', schema=None) as batch_op:
        batch_op.create_index('ix_delegation_offer_task_status', ['delegated_task_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_offers_delegated_task_id'), ['delegated_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegation_offers_repliker_id'), ['repliker_id'], unique=False)

    op.create_table('qa_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('criterion_result_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('tool_execution_log_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('artifact', 'tool_execution', 'system')", name='ck_qa_evidence_type'),
    sa.ForeignKeyConstraint(['artifact_id'], ['execution_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criterion_result_id'], ['qa_criterion_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['qa_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_execution_log_id'], ['tool_execution_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_evidence_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_evidence_criterion_result_id'), ['criterion_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_evidence_evidence_type'), ['evidence_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_evidence_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_evidence_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_evidence_tool_execution_log_id'), ['tool_execution_log_id'], unique=False)

    op.create_table('subcontracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegation_request_id', sa.Integer(), nullable=False),
    sa.Column('delegated_task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('root_contract_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('delegator_repliker_id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_repliker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reserved_cents', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('selection_score', sa.Integer(), nullable=False),
    sa.Column('pricing_policy_version', sa.String(length=40), nullable=False),
    sa.Column('selection_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('awarded', 'active', 'completed', 'failed', 'cancelled')", name='ck_subcontract_status'),
    sa.CheckConstraint('amount_cents > 0', name='ck_subcontract_amount_positive'),
    sa.CheckConstraint('depth >= 1', name='ck_subcontract_depth'),
    sa.CheckConstraint('reserved_cents >= 0', name='ck_subcontract_reserved_nonnegative'),
    sa.ForeignKeyConstraint(['delegated_task_id'], ['delegated_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegation_request_id'], ['delegation_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegator_repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_contract_id'], ['task_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcontractor_repliker_id'], ['replikers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcontracts', schema=None) as batch_op:
        batch_op.create_index('ix_subcontract_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('ix_subcontract_root_contract', ['root_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_delegated_task_id'), ['delegated_task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_subcontracts_delegation_request_id'), ['delegation_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_subcontracts_delegator_repliker_id'), ['delegator_repliker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_root_contract_id'), ['root_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_subcontractor_repliker_id'), ['subcontractor_repliker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontracts_subcontractor_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_status'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_root_contract_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_project_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_delegator_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_delegation_request_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_delegated_task_id'))
        batch_op.drop_index('ix_subcontract_root_contract')
        batch_op.drop_index('ix_subcontract_project_status')

    op.drop_table('subcontracts')
    with op.batch_alter_table('qa_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_evidence_tool_execution_log_id'))
        batch_op.drop_index(batch_op.f('ix_qa_evidence_review_id'))
        batch_op.drop_index(batch_op.f('ix_qa_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_qa_evidence_evidence_type'))
        batch_op.drop_index(batch_op.f('ix_qa_evidence_criterion_result_id'))
        batch_op.drop_index(batch_op.f('ix_qa_evidence_artifact_id'))

    op.drop_table('qa_evidence')
    with op.batch_alter_table('delegation_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegation_offers_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_offers_delegated_task_id'))
        batch_op.drop_index('ix_delegation_offer_task_status')

    op.drop_table('delegation_offers')
    with op.batch_alter_table('qa_retry_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_retry_runs_status'))
        batch_op.drop_index(batch_op.f('ix_qa_retry_runs_source_review_id'))
        batch_op.drop_index(batch_op.f('ix_qa_retry_runs_next_review_id'))
        batch_op.drop_index(batch_op.f('ix_qa_retry_runs_contract_id'))

    op.drop_table('qa_retry_runs')
    with op.batch_alter_table('qa_reputation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_reputation_events_review_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reputation_events_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reputation_events_contract_id'))

    op.drop_table('qa_reputation_events')
    with op.batch_alter_table('qa_criterion_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_criterion_results_status'))
        batch_op.drop_index(batch_op.f('ix_qa_criterion_results_review_id'))
        batch_op.drop_index(batch_op.f('ix_qa_criterion_results_id'))
        batch_op.drop_index(batch_op.f('ix_qa_criterion_results_criterion_id'))

    op.drop_table('qa_criterion_results')
    with op.batch_alter_table('delegated_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegated_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_delegated_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_delegated_tasks_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_delegated_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_delegated_tasks_delegation_request_id'))
        batch_op.drop_index('ix_delegated_task_project_status')

    op.drop_table('delegated_tasks')
    with op.batch_alter_table('tool_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_execution_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tool_execution_logs_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_execution_logs_status'))
        batch_op.drop_index(batch_op.f('ix_tool_execution_logs_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_tool_execution_logs_id'))
        batch_op.drop_index(batch_op.f('ix_tool_execution_logs_contract_id'))

    op.drop_table('tool_execution_logs')
    with op.batch_alter_table('qa_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_reviews_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reviews_task_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_qa_reviews_reviewer_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reviews_execution_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_qa_reviews_contract_id'))

    op.drop_table('qa_reviews')
    with op.batch_alter_table('execution_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_id'))

    op.drop_table('execution_artifacts')
    with op.batch_alter_table('delegation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegation_requests_status'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_root_contract_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_parent_request_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_delegator_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_delegation_requests_collaboration_thread_id'))
        batch_op.drop_index('ix_delegation_project_status')

    op.drop_table('delegation_requests')
    with op.batch_alter_table('collaboration_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaboration_participants_thread_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_participants_repliker_id'))
        batch_op.drop_index('ix_collaboration_participant_repliker')

    op.drop_table('collaboration_participants')
    with op.batch_alter_table('collaboration_message_states', schema=None) as batch_op:
        batch_op.drop_index('ix_collaboration_state_thread_status')
        batch_op.drop_index(batch_op.f('ix_collaboration_message_states_thread_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_message_states_reply_to_message_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_message_states_message_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_message_states_contract_id'))

    op.drop_table('collaboration_message_states')
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_to_account_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_project_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_initiated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_from_account_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_external_reference'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_currency'))
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_contract_id'))
        batch_op.drop_index('ix_ledger_transaction_repliker')
        batch_op.drop_index('ix_ledger_transaction_project_created')
        batch_op.drop_index('ix_ledger_transaction_contract')

    op.drop_table('ledger_transactions')
    with op.batch_alter_table('execution_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_workspaces_task_id'))
        batch_op.drop_index(batch_op.f('ix_execution_workspaces_status'))
        batch_op.drop_index(batch_op.f('ix_execution_workspaces_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_execution_workspaces_project_id'))
        batch_op.drop_index(batch_op.f('ix_execution_workspaces_id'))
        batch_op.drop_index(batch_op.f('ix_execution_workspaces_contract_id'))

    op.drop_table('execution_workspaces')
    with op.batch_alter_table('collaboration_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaboration_threads_task_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_threads_status'))
        batch_op.drop_index(batch_op.f('ix_collaboration_threads_project_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_threads_kind'))
        batch_op.drop_index(batch_op.f('ix_collaboration_threads_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_threads_contract_id'))
        batch_op.drop_index('ix_collaboration_thread_task')
        batch_op.drop_index('ix_collaboration_thread_project_status')

    op.drop_table('collaboration_threads')
    with op.batch_alter_table('task_contracts', schema=None) as batch_op:
        batch_op.drop_index('uq_task_contract_active', sqlite_where=sa.text("status IN ('awarded', 'active')"), postgresql_where=sa.text("status IN ('awarded', 'active')"))
        batch_op.drop_index(batch_op.f('ix_task_contracts_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_task_contracts_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_task_contracts_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_task_contracts_bid_id'))
        batch_op.drop_index('ix_task_contract_project_status')

    op.drop_table('task_contracts')
    with op.batch_alter_table('task_skill_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_skill_requirements_task_id'))

    op.drop_table('task_skill_requirements')
    with op.batch_alter_table('task_bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_bids_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_bids_repliker_id'))

    op.drop_table('task_bids')
    with op.batch_alter_table('task_acceptance_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_acceptance_criteria_task_id'))

    op.drop_table('task_acceptance_criteria')
    with op.batch_alter_table('repliker_task_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repliker_task_decisions_task_id'))
        batch_op.drop_index(batch_op.f('ix_repliker_task_decisions_repliker_id'))

    op.drop_table('repliker_task_decisions')
    with op.batch_alter_table('realtime_events', schema=None) as batch_op:
        batch_op.drop_index('ix_realtime_repliker_cursor')
        batch_op.drop_index('ix_realtime_project_cursor')
        batch_op.drop_index(batch_op.f('ix_realtime_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_events_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_events_kind'))
        batch_op.drop_index(batch_op.f('ix_realtime_events_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_events_event_type'))

    op.drop_table('realtime_events')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_sender_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_receiver_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_project_id'))

    op.drop_table('agent_messages')
    with op.batch_alter_table('agent_activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_activity_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activity_events_repliker_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activity_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activity_events_event_type'))

    op.drop_table('agent_activity_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('repliker_tool_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repliker_tool_assignments_tool_name'))
        batch_op.drop_index(batch_op.f('ix_repliker_tool_assignments_repliker_id'))

    op.drop_table('repliker_tool_assignments')
    with op.batch_alter_table('repliker_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repliker_skills_repliker_id'))

    op.drop_table('repliker_skills')
    with op.batch_alter_table('repliker_appearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repliker_appearances_repliker_id'))

    op.drop_table('repliker_appearances')
    with op.batch_alter_table('project_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_requirements_project_id'))

    op.drop_table('project_requirements')
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_project_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_kind'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_currency'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_account_key'))
        batch_op.drop_index('ix_ledger_account_user_kind_currency')
        batch_op.drop_index('ix_ledger_account_project_kind_currency')

    op.drop_table('ledger_accounts')
    with op.batch_alter_table('replikers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replikers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_replikers_id'))

    op.drop_table('replikers')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_client_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
